### ISSUE TITLE
yarn dev is not running the project

### ISSUE THREAD

**Issue by ahmadrfx** [oluwadareseyi/folio-v2#3]
After installing all dependencies using yarn, \yarn dev\ isn't kick starting the project

**Comment by Stealthy-CodeWalker** [comment]
Once you have finished building the node modules using `yarn` or `npm install`, switch to Bash profile on Vscode in order to run the project with `yarn dev` or `npm run dev`. Those `rm -rf` commands are exclusive to Bash.

**Comment by ahmadrfx** [comment]
Thanks, It now works
